In [1]:
x=1
y=5
x+y

6

In [2]:
x


1

In [3]:
def add_numbers=(x,y):
    return x+y

add_numbers=(8,10)

SyntaxError: invalid syntax (<ipython-input-3-828bced258a6>, line 1)

In [4]:
def add_numbers(x,y):
    return x+y

add_numbers=(8,10)

In [5]:
def add_numbers(x, y):
    return x + y

add_numbers(8,10)

18

In [6]:
def add_numbers(x, y, z):
    return x + y + z

add_numbers(8, 10, 15)

33

In [7]:
def add_numbers(x, y, z=None):
    if (z == None):
        return x + y
    else:
        return x + y + z
    
    
print(add_numbers(2,4))
print(add_numbers(2,4,6))

6
12


In [8]:
def do_math(?, ?, ?):
  if (kind=='add'):
    return a+b
  else:
    return a-b

do_math(1, 2)

SyntaxError: invalid syntax (<ipython-input-8-62dd5f2e63fc>, line 1)

In [9]:
def do_math(a, b, kind=add):
  if (kind==add):
    return a+b
  else:
    return a-b

print(do_math(1, 2))

NameError: name 'add' is not defined

In [10]:
type(add_number)


NameError: name 'add_number' is not defined

In [11]:
type(add_numbers)

function

In [12]:
x = (1, 'a', 2, 'b')

In [13]:
type(x)

tuple

In [14]:
x = [1, 'a', 2, 'b']

In [15]:
type(x)

list

In [16]:
x.append(3.3)

In [17]:
print(x)

[1, 'a', 2, 'b', 3.3]


In [18]:
from item in (x):
    print item;
    

SyntaxError: invalid syntax (<ipython-input-18-80c07a0279f7>, line 1)

In [19]:
for item in (x):
    print (item)

1
a
2
b
3.3


In [20]:
i= 0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


In [21]:
[1, 2] + [3, 4]


[1, 2, 3, 4]

In [22]:
1 in [1, 4, 8]

True

In [23]:
2 in [1, 4, 8]

False

In [25]:
x = 'Dr. Christopher Brooks'

print(x[4:-7])

Christopher


In [26]:
x = {'karangondalia' : 'karan.gondalia@gmail.com' , 'messi' : 'messi@gmail'}
x[messi]

NameError: name 'messi' is not defined

In [27]:
x['messi']

'messi@gmail'

In [28]:
x['ronaldo'] = None
x['ronaldo']

In [29]:
for name in x:
    print(x[name])

messi@gmail
None
karan.gondalia@gmail.com


In [30]:
for email in x.values():
    print(email)

messi@gmail
None
karan.gondalia@gmail.com


In [31]:
for name,email in x.items():
    print(name)
    print(email)

messi
messi@gmail
ronaldo
None
karangondalia
karan.gondalia@gmail.com


In [32]:
#DATA FILES AND SUMMARY STATISTICS

In [33]:
import csv

%precision 2



u'%.2f'

In [34]:





i

5

In [35]:
import datetime as dt
import time as tm

In [36]:
tm.time()

1527352372.52

In [37]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2018, 5, 26, 22, 4, 17, 489790)

In [38]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [39]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range (10)]

True

In [40]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = []
correct_answer == answer

NameError: name 'correct_answer' is not defined

In [41]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

correct_answer[:50] # Display first 50 ids


['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa29',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa39',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa49']

In [42]:
#NUMPY

In [46]:
import numpy as np

In [47]:
m = np.array([[7,8,9],[12,13,15]])

In [48]:
m

array([[ 7,  8,  9],
       [12, 13, 15]])

In [49]:
m.shape


(2, 3)

In [50]:
n = np.arange(0,30,2)

In [51]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [53]:
n = n.reshape(3,5)

n

In [54]:
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [55]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [56]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old.copy()
new[:, 0] = 0

print(old)

[[1 1 1]
 [1 1 1]]


In [57]:
type(lambda x: x+1)

function

In [2]:
import pandas as pd
pd.Series?

In [3]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [4]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [5]:
animals = ['Tiger', 'Bear', None]
pd.Series(animals)

0    Tiger
1     Bear
2     None
dtype: object

In [6]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [7]:
import numpy as np
np.nan == None

False

In [8]:
np.nan == np.nan

False

In [9]:
np.isnan(np.nan)

True

In [10]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s


Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [11]:
s.index

Index([u'Archery', u'Golf', u'Sumo', u'Taekwondo'], dtype='object')

In [12]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s

India      Tiger
America     Bear
Canada     Moose
dtype: object

In [2]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

NameError: name 'pd' is not defined

In [4]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [3]:
import pandas as pd

In [5]:
s.iloc[3]

'South Korea'

In [1]:
import pandas as pd

In [2]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [3]:
s.iloc[3]

'South Korea'

In [4]:
s.loc['Taekwondo']

'South Korea'

In [6]:
s.iloc[2]

'Japan'

In [7]:
s[2]

'Japan'

In [8]:
s['Golf']

'Scotland'

In [9]:
s = pd.Series([100.00,120.00,101.00,3.00])
s

0    100.0
1    120.0
2    101.0
3      3.0
dtype: float64

In [10]:
total = 0
for item in s:
    total += item
print(total)    

324.0


In [11]:
import numpy as np


In [12]:
total = np.sum(s)

In [13]:
print(total)

324.0


In [14]:
s = pd.Series(np.random.randint(0,1000,100000))

In [17]:
s.head()

0    954
1    459
2    329
3    258
4    824
dtype: int64

In [18]:
s.head()

0    954
1    459
2    329
3    258
4    824
dtype: int64

In [19]:
len(s)

100000

In [23]:
%%timeit -n 1000
summary = 0
for item in s:
    summary += item

1000 loops, best of 3: 5.78 ms per loop


In [21]:
s.head()

0    954
1    459
2    329
3    258
4    824
dtype: int64

In [24]:
%%timeit -n 1000
summary = np.sum(s)

1000 loops, best of 3: 666 µs per loop


In [26]:
s -= 2
s.head()

0    954
1    459
2    329
3    258
4    824
dtype: int64

In [27]:
for label,values in s.iteritems():
    s.set_value(label,values+2)
s.head()    

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  


0    956
1    461
2    331
3    260
4    826
dtype: int64

In [29]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
for label, value in s.iteritems():
    s.loc[label]= value+2

KeyboardInterrupt: 

In [ ]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,100000))
s += 2

In [30]:
s = pd.Series([1, 2, 3])
s.loc['Animal'] = 'Bears'
s

0             1
1             2
2             3
Animal    Bears
dtype: object

In [31]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)

In [32]:
original_sports

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [33]:
cricket_loving_countries

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

In [34]:
all_countries

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
Cricket        Australia
Cricket         Barbados
Cricket         Pakistan
Cricket          England
dtype: object

In [35]:
all_countries.loc['Cricket']

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

In [36]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])

In [37]:
df

Cost Item Purchased   Name
Store 1  22.5       Dog Food  Chris
Store 1   2.5   Kitty Litter  Kevyn
Store 2   5.0      Bird Seed  Vinod

In [38]:
type(df)

pandas.core.frame.DataFrame

In [39]:
df.loc['Store 2']

Cost                      5
Item Purchased    Bird Seed
Name                  Vinod
Name: Store 2, dtype: object

In [41]:
type(df.loc['Store 1'])

pandas.core.frame.DataFrame

In [42]:
df.loc['Store 1', 'Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [43]:
df.T

Store 1       Store 1    Store 2
Cost                22.5           2.5          5
Item Purchased  Dog Food  Kitty Litter  Bird Seed
Name               Chris         Kevyn      Vinod

In [44]:
df.T.loc['Cost']

Store 1    22.5
Store 1     2.5
Store 2       5
Name: Cost, dtype: object

In [45]:
df['Cost']

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [46]:
df


Cost Item Purchased   Name
Store 1  22.5       Dog Food  Chris
Store 1   2.5   Kitty Litter  Kevyn
Store 2   5.0      Bird Seed  Vinod

In [47]:
df['Cost']

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [48]:
df.loc['Store 1']['Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [49]:
df.loc[:,['Name', 'Cost']]

Name  Cost
Store 1  Chris  22.5
Store 1  Kevyn   2.5
Store 2  Vinod   5.0

In [51]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])

df

Cost Item Purchased   Name
Store 1  22.5       Dog Food  Chris
Store 1   2.5   Kitty Litter  Kevyn
Store 2   5.0      Bird Seed  Vinod

In [52]:

df['Cost'] *= 0.8
print(df)

         Cost Item Purchased   Name
Store 1  18.0       Dog Food  Chris
Store 1   2.0   Kitty Litter  Kevyn
Store 2   4.0      Bird Seed  Vinod


In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])


df[df['Cost'] > 3.00]

Cost Item Purchased   Name
Store 1  22.5       Dog Food  Chris
Store 2   5.0      Bird Seed  Vinod

In [4]:
df['Name'][df['Cost']>3]

Store 1    Chris
Store 2    Vinod
Name: Name, dtype: object

In [13]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])


# Your answer here

df = df.set_index([df.index , 'Cost'])
df

Item Purchased   Name
        Cost                      
Store 1 22.5       Dog Food  Chris
        2.5    Kitty Litter  Kevyn
Store 2 5.0       Bird Seed  Vinod

In [14]:
df.index.names = ['Location', 'Cost']
df

Item Purchased   Name
Location Cost                      
Store 1  22.5       Dog Food  Chris
         2.5    Kitty Litter  Kevyn
Store 2  5.0       Bird Seed  Vinod

In [9]:
df = df.append(pd.Series(data={'Cost': 3.00, 'Item Purchased': 'Kitty Food'}, name=('Store 2', 'Kevyn')))

In [10]:
df

Cost Item Purchased
Location Name                      
Store 1  Chris  22.5       Dog Food
         Kevyn   2.5   Kitty Litter
Store 2  Vinod   5.0      Bird Seed
         Kevyn   3.0     Kitty Food

In [15]:
df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

In [16]:
df


Empty DataFrame
Columns: []
Index: [Afghanistan (AFG)	13	0	0	2	2	0	0	0	0	0	13	0	0	2	2, Algeria (ALG)	12	5	2	8	15	3	0	0	0	0	15	5	2	8	15, Argentina (ARG)	23	18	24	28	70	18	0	0	0	0	41	18	24	28	70, Armenia (ARM)	5	1	2	9	12	6	0	0	0	0	11	1	2	9	12, Australasia (ANZ) [ANZ]	2	3	4	5	12	0	0	0	0	0	2	3	4	5	12, Australia (AUS) [AUS] [Z]	25	139	152	177	468	18	5	3	4	12	43	144	155	181	480, Austria (AUT)	26	18	33	35	86	22	59	78	81	218	48	77	111	116	304, Azerbaijan (AZE)	5	6	5	15	26	5	0	0	0	0	10	6	5	15	26, Bahamas (BAH)	15	5	2	5	12	0	0	0	0	0	15	5	2	5	12, Bahrain (BRN)	8	0	0	1	1	0	0	0	0	0	8	0	0	1	1, Barbados (BAR) [BAR]	11	0	0	1	1	0	0	0	0	0	11	0	0	1	1, Belarus (BLR)	5	12	24	39	75	6	6	4	5	15	11	18	28	44	90, Belgium (BEL)	25	37	52	53	142	20	1	1	3	5	45	38	53	56	147, Bermuda (BER)	17	0	0	1	1	7	0	0	0	0	24	0	0	1	1, Bohemia (BOH) [BOH] [Z]	3	0	1	3	4	0	0	0	0	0	3	0	1	3	4, Botswana (BOT)	9	0	1	0	1	0	0	0	0	0	9	0	1	0	1, Brazil (BRA)	21	23	30	55	108	7	0	0	0	0	28	23	30	55	108, British West Indies (BWI) [BWI]	1	0	0	2	2	0	0	0	0	0	1	0	0	2	2, Bulgaria (BUL) [H]	19	51	85	78	214	19	1	2	3	6	38	52	87	81	220, Burundi (BDI)	5	1	0	0	1	0	0	0	0	0	5	1	0	0	1, Cameroon (CMR)	13	3	1	1	5	1	0	0	0	0	14	3	1	1	5, Canada (CAN)	25	59	99	121	279	22	62	56	52	170	47	121	155	173	449, Chile (CHI) [I]	22	2	7	4	13	16	0	0	0	0	38	2	7	4	13, China (CHN) [CHN]	9	201	146	126	473	10	12	22	19	53	19	213	168	145	526, Colombia (COL)	18	2	6	11	19	1	0	0	0	0	19	2	6	11	19, Costa Rica (CRC)	14	1	1	2	4	6	0	0	0	0	20	1	1	2	4, Ivory Coast (CIV) [CIV]	12	0	1	0	1	0	0	0	0	0	12	0	1	0	1, Croatia (CRO)	6	6	7	10	23	7	4	6	1	11	13	10	13	11	34, Cuba (CUB) [Z]	19	72	67	70	209	0	0	0	0	0	19	72	67	70	209, Cyprus (CYP)	9	0	1	0	1	10	0	0	0	0	19	0	1	0	1, Czech Republic (CZE) [CZE]	5	14	15	15	44	6	7	9	8	24	11	21	24	23	68, Czechoslovakia (TCH) [TCH]	16	49	49	45	143	16	2	8	15	25	32	51	57	60	168, Denmark (DEN) [Z]	26	43	68	68	179	13	0	1	0	1	39	43	69	68	180, Djibouti (DJI) [B]	7	0	0	1	1	0	0	0	0	0	7	0	0	1	1, Dominican Republic (DOM)	13	3	2	1	6	0	0	0	0	0	13	3	2	1	6, Ecuador (ECU)	13	1	1	0	2	0	0	0	0	0	13	1	1	0	2, Egypt (EGY) [EGY] [Z]	21	7	9	10	26	1	0	0	0	0	22	7	9	10	26, Eritrea (ERI)	4	0	0	1	1	0	0	0	0	0	4	0	0	1	1, Estonia (EST)	11	9	9	15	33	9	4	2	1	7	20	13	11	16	40, Ethiopia (ETH)	12	21	7	17	45	2	0	0	0	0	14	21	7	17	45, Finland (FIN)	24	101	84	117	302	22	42	62	57	161	46	143	146	174	463, France (FRA) [O] [P] [Z]	27	202	223	246	671	22	31	31	47	109	49	233	254	293	780, Gabon (GAB)	9	0	1	0	1	0	0	0	0	0	9	0	1	0	1, Georgia (GEO)	5	6	5	14	25	6	0	0	0	0	11	6	5	14	25, Germany (GER) [GER] [Z]	15	174	182	217	573	11	78	78	53	209	26	252	260	270	782, United Team of Germany (EUA) [EUA]	3	28	54	36	118	3	8	6	5	19	6	36	60	41	137, East Germany (GDR) [GDR]	5	153	129	127	409	6	39	36	35	110	11	192	165	162	519, West Germany (FRG) [FRG]	5	56	67	81	204	6	11	15	13	39	11	67	82	94	243, Ghana (GHA) [GHA]	13	0	1	3	4	1	0	0	0	0	14	0	1	3	4, Great Britain (GBR) [GBR] [Z]	27	236	272	272	780	22	10	4	12	26	49	246	276	284	806, Greece (GRE) [Z]	27	30	42	39	111	18	0	0	0	0	45	30	42	39	111, Grenada (GRN)	8	1	0	0	1	0	0	0	0	0	8	1	0	0	1, Guatemala (GUA)	13	0	1	0	1	1	0	0	0	0	14	0	1	0	1, Guyana (GUY) [GUY]	16	0	0	1	1	0	0	0	0	0	16	0	0	1	1, Haiti (HAI) [J]	14	0	1	1	2	0	0	0	0	0	14	0	1	1	2, Hong Kong (HKG) [HKG]	15	1	1	1	3	4	0	0	0	0	19	1	1	1	3, Hungary (HUN)	25	167	144	165	476	22	0	2	4	6	47	167	146	169	482, Iceland (ISL)	19	0	2	2	4	17	0	0	0	0	36	0	2	2	4, India (IND) [F]	23	9	6	11	26	9	0	0	0	0	32	9	6	11	26, Indonesia (INA)	14	6	10	11	27	0	0	0	0	0	14	6	10	11	27, Iran (IRI) [K]	15	15	20	25	60	10	0	0	0	0	25	15	20	25	60, Iraq (IRQ)	13	0	0	1	1	0	0	0	0	0	13	0	0	1	1, Ireland (IRL)	20	9	8	12	29	6	0	0	0	0	26	9	8	12	29, Israel (ISR)	15	1	1	5	7	6	0	0	0	0	21	1	1	5	7, Italy (ITA) [M] [S]	26	198	166	185	549	22	37	34	43	114	48	235	200	228	663, Jamaica (JAM) [JAM]	16	17	30	20	67	7	0	0	0	0	23	17	30	20	67, Japan (JPN)	21	130	126	142	398	20	10	17	18	45	41	140	143	160	443, Kazakhstan (KAZ)	5	16	17	19	52	6	1	3	3	7	11	17	20	22	59, Kenya (KEN)	13	25	32	29	86	3	0	0	0	0	16	25	32	29	86, North Korea (PRK)	9	14	12	21

In [17]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)

In [18]:
df

Empty DataFrame
Columns: []
Index: [Afghanistan (AFG)	13	0	0	2	2	0	0	0	0	0	13	0	0	2	2, Algeria (ALG)	12	5	2	8	15	3	0	0	0	0	15	5	2	8	15, Argentina (ARG)	23	18	24	28	70	18	0	0	0	0	41	18	24	28	70, Armenia (ARM)	5	1	2	9	12	6	0	0	0	0	11	1	2	9	12, Australasia (ANZ) [ANZ]	2	3	4	5	12	0	0	0	0	0	2	3	4	5	12, Australia (AUS) [AUS] [Z]	25	139	152	177	468	18	5	3	4	12	43	144	155	181	480, Austria (AUT)	26	18	33	35	86	22	59	78	81	218	48	77	111	116	304, Azerbaijan (AZE)	5	6	5	15	26	5	0	0	0	0	10	6	5	15	26, Bahamas (BAH)	15	5	2	5	12	0	0	0	0	0	15	5	2	5	12, Bahrain (BRN)	8	0	0	1	1	0	0	0	0	0	8	0	0	1	1, Barbados (BAR) [BAR]	11	0	0	1	1	0	0	0	0	0	11	0	0	1	1, Belarus (BLR)	5	12	24	39	75	6	6	4	5	15	11	18	28	44	90, Belgium (BEL)	25	37	52	53	142	20	1	1	3	5	45	38	53	56	147, Bermuda (BER)	17	0	0	1	1	7	0	0	0	0	24	0	0	1	1, Bohemia (BOH) [BOH] [Z]	3	0	1	3	4	0	0	0	0	0	3	0	1	3	4, Botswana (BOT)	9	0	1	0	1	0	0	0	0	0	9	0	1	0	1, Brazil (BRA)	21	23	30	55	108	7	0	0	0	0	28	23	30	55	108, British West Indies (BWI) [BWI]	1	0	0	2	2	0	0	0	0	0	1	0	0	2	2, Bulgaria (BUL) [H]	19	51	85	78	214	19	1	2	3	6	38	52	87	81	220, Burundi (BDI)	5	1	0	0	1	0	0	0	0	0	5	1	0	0	1, Cameroon (CMR)	13	3	1	1	5	1	0	0	0	0	14	3	1	1	5, Canada (CAN)	25	59	99	121	279	22	62	56	52	170	47	121	155	173	449, Chile (CHI) [I]	22	2	7	4	13	16	0	0	0	0	38	2	7	4	13, China (CHN) [CHN]	9	201	146	126	473	10	12	22	19	53	19	213	168	145	526, Colombia (COL)	18	2	6	11	19	1	0	0	0	0	19	2	6	11	19, Costa Rica (CRC)	14	1	1	2	4	6	0	0	0	0	20	1	1	2	4, Ivory Coast (CIV) [CIV]	12	0	1	0	1	0	0	0	0	0	12	0	1	0	1, Croatia (CRO)	6	6	7	10	23	7	4	6	1	11	13	10	13	11	34, Cuba (CUB) [Z]	19	72	67	70	209	0	0	0	0	0	19	72	67	70	209, Cyprus (CYP)	9	0	1	0	1	10	0	0	0	0	19	0	1	0	1, Czech Republic (CZE) [CZE]	5	14	15	15	44	6	7	9	8	24	11	21	24	23	68, Czechoslovakia (TCH) [TCH]	16	49	49	45	143	16	2	8	15	25	32	51	57	60	168, Denmark (DEN) [Z]	26	43	68	68	179	13	0	1	0	1	39	43	69	68	180, Djibouti (DJI) [B]	7	0	0	1	1	0	0	0	0	0	7	0	0	1	1, Dominican Republic (DOM)	13	3	2	1	6	0	0	0	0	0	13	3	2	1	6, Ecuador (ECU)	13	1	1	0	2	0	0	0	0	0	13	1	1	0	2, Egypt (EGY) [EGY] [Z]	21	7	9	10	26	1	0	0	0	0	22	7	9	10	26, Eritrea (ERI)	4	0	0	1	1	0	0	0	0	0	4	0	0	1	1, Estonia (EST)	11	9	9	15	33	9	4	2	1	7	20	13	11	16	40, Ethiopia (ETH)	12	21	7	17	45	2	0	0	0	0	14	21	7	17	45, Finland (FIN)	24	101	84	117	302	22	42	62	57	161	46	143	146	174	463, France (FRA) [O] [P] [Z]	27	202	223	246	671	22	31	31	47	109	49	233	254	293	780, Gabon (GAB)	9	0	1	0	1	0	0	0	0	0	9	0	1	0	1, Georgia (GEO)	5	6	5	14	25	6	0	0	0	0	11	6	5	14	25, Germany (GER) [GER] [Z]	15	174	182	217	573	11	78	78	53	209	26	252	260	270	782, United Team of Germany (EUA) [EUA]	3	28	54	36	118	3	8	6	5	19	6	36	60	41	137, East Germany (GDR) [GDR]	5	153	129	127	409	6	39	36	35	110	11	192	165	162	519, West Germany (FRG) [FRG]	5	56	67	81	204	6	11	15	13	39	11	67	82	94	243, Ghana (GHA) [GHA]	13	0	1	3	4	1	0	0	0	0	14	0	1	3	4, Great Britain (GBR) [GBR] [Z]	27	236	272	272	780	22	10	4	12	26	49	246	276	284	806, Greece (GRE) [Z]	27	30	42	39	111	18	0	0	0	0	45	30	42	39	111, Grenada (GRN)	8	1	0	0	1	0	0	0	0	0	8	1	0	0	1, Guatemala (GUA)	13	0	1	0	1	1	0	0	0	0	14	0	1	0	1, Guyana (GUY) [GUY]	16	0	0	1	1	0	0	0	0	0	16	0	0	1	1, Haiti (HAI) [J]	14	0	1	1	2	0	0	0	0	0	14	0	1	1	2, Hong Kong (HKG) [HKG]	15	1	1	1	3	4	0	0	0	0	19	1	1	1	3, Hungary (HUN)	25	167	144	165	476	22	0	2	4	6	47	167	146	169	482, Iceland (ISL)	19	0	2	2	4	17	0	0	0	0	36	0	2	2	4, India (IND) [F]	23	9	6	11	26	9	0	0	0	0	32	9	6	11	26, Indonesia (INA)	14	6	10	11	27	0	0	0	0	0	14	6	10	11	27, Iran (IRI) [K]	15	15	20	25	60	10	0	0	0	0	25	15	20	25	60, Iraq (IRQ)	13	0	0	1	1	0	0	0	0	0	13	0	0	1	1, Ireland (IRL)	20	9	8	12	29	6	0	0	0	0	26	9	8	12	29, Israel (ISR)	15	1	1	5	7	6	0	0	0	0	21	1	1	5	7, Italy (ITA) [M] [S]	26	198	166	185	549	22	37	34	43	114	48	235	200	228	663, Jamaica (JAM) [JAM]	16	17	30	20	67	7	0	0	0	0	23	17	30	20	67, Japan (JPN)	21	130	126	142	398	20	10	17	18	45	41	140	143	160	443, Kazakhstan (KAZ)	5	16	17	19	52	6	1	3	3	7	11	17	20	22	59, Kenya (KEN)	13	25	32	29	86	3	0	0	0	0	16	25	32	29	86, North Korea (PRK)	9	14	12	21

In [19]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

In [20]:
df

Empty DataFrame
Columns: []
Index: [Afghanistan (AFG)	13	0	0	2	2	0	0	0	0	0	13	0	0	2	2, Algeria (ALG)	12	5	2	8	15	3	0	0	0	0	15	5	2	8	15, Argentina (ARG)	23	18	24	28	70	18	0	0	0	0	41	18	24	28	70, Armenia (ARM)	5	1	2	9	12	6	0	0	0	0	11	1	2	9	12, Australasia (ANZ) [ANZ]	2	3	4	5	12	0	0	0	0	0	2	3	4	5	12, Australia (AUS) [AUS] [Z]	25	139	152	177	468	18	5	3	4	12	43	144	155	181	480, Austria (AUT)	26	18	33	35	86	22	59	78	81	218	48	77	111	116	304, Azerbaijan (AZE)	5	6	5	15	26	5	0	0	0	0	10	6	5	15	26, Bahamas (BAH)	15	5	2	5	12	0	0	0	0	0	15	5	2	5	12, Bahrain (BRN)	8	0	0	1	1	0	0	0	0	0	8	0	0	1	1, Barbados (BAR) [BAR]	11	0	0	1	1	0	0	0	0	0	11	0	0	1	1, Belarus (BLR)	5	12	24	39	75	6	6	4	5	15	11	18	28	44	90, Belgium (BEL)	25	37	52	53	142	20	1	1	3	5	45	38	53	56	147, Bermuda (BER)	17	0	0	1	1	7	0	0	0	0	24	0	0	1	1, Bohemia (BOH) [BOH] [Z]	3	0	1	3	4	0	0	0	0	0	3	0	1	3	4, Botswana (BOT)	9	0	1	0	1	0	0	0	0	0	9	0	1	0	1, Brazil (BRA)	21	23	30	55	108	7	0	0	0	0	28	23	30	55	108, British West Indies (BWI) [BWI]	1	0	0	2	2	0	0	0	0	0	1	0	0	2	2, Bulgaria (BUL) [H]	19	51	85	78	214	19	1	2	3	6	38	52	87	81	220, Burundi (BDI)	5	1	0	0	1	0	0	0	0	0	5	1	0	0	1, Cameroon (CMR)	13	3	1	1	5	1	0	0	0	0	14	3	1	1	5, Canada (CAN)	25	59	99	121	279	22	62	56	52	170	47	121	155	173	449, Chile (CHI) [I]	22	2	7	4	13	16	0	0	0	0	38	2	7	4	13, China (CHN) [CHN]	9	201	146	126	473	10	12	22	19	53	19	213	168	145	526, Colombia (COL)	18	2	6	11	19	1	0	0	0	0	19	2	6	11	19, Costa Rica (CRC)	14	1	1	2	4	6	0	0	0	0	20	1	1	2	4, Ivory Coast (CIV) [CIV]	12	0	1	0	1	0	0	0	0	0	12	0	1	0	1, Croatia (CRO)	6	6	7	10	23	7	4	6	1	11	13	10	13	11	34, Cuba (CUB) [Z]	19	72	67	70	209	0	0	0	0	0	19	72	67	70	209, Cyprus (CYP)	9	0	1	0	1	10	0	0	0	0	19	0	1	0	1, Czech Republic (CZE) [CZE]	5	14	15	15	44	6	7	9	8	24	11	21	24	23	68, Czechoslovakia (TCH) [TCH]	16	49	49	45	143	16	2	8	15	25	32	51	57	60	168, Denmark (DEN) [Z]	26	43	68	68	179	13	0	1	0	1	39	43	69	68	180, Djibouti (DJI) [B]	7	0	0	1	1	0	0	0	0	0	7	0	0	1	1, Dominican Republic (DOM)	13	3	2	1	6	0	0	0	0	0	13	3	2	1	6, Ecuador (ECU)	13	1	1	0	2	0	0	0	0	0	13	1	1	0	2, Egypt (EGY) [EGY] [Z]	21	7	9	10	26	1	0	0	0	0	22	7	9	10	26, Eritrea (ERI)	4	0	0	1	1	0	0	0	0	0	4	0	0	1	1, Estonia (EST)	11	9	9	15	33	9	4	2	1	7	20	13	11	16	40, Ethiopia (ETH)	12	21	7	17	45	2	0	0	0	0	14	21	7	17	45, Finland (FIN)	24	101	84	117	302	22	42	62	57	161	46	143	146	174	463, France (FRA) [O] [P] [Z]	27	202	223	246	671	22	31	31	47	109	49	233	254	293	780, Gabon (GAB)	9	0	1	0	1	0	0	0	0	0	9	0	1	0	1, Georgia (GEO)	5	6	5	14	25	6	0	0	0	0	11	6	5	14	25, Germany (GER) [GER] [Z]	15	174	182	217	573	11	78	78	53	209	26	252	260	270	782, United Team of Germany (EUA) [EUA]	3	28	54	36	118	3	8	6	5	19	6	36	60	41	137, East Germany (GDR) [GDR]	5	153	129	127	409	6	39	36	35	110	11	192	165	162	519, West Germany (FRG) [FRG]	5	56	67	81	204	6	11	15	13	39	11	67	82	94	243, Ghana (GHA) [GHA]	13	0	1	3	4	1	0	0	0	0	14	0	1	3	4, Great Britain (GBR) [GBR] [Z]	27	236	272	272	780	22	10	4	12	26	49	246	276	284	806, Greece (GRE) [Z]	27	30	42	39	111	18	0	0	0	0	45	30	42	39	111, Grenada (GRN)	8	1	0	0	1	0	0	0	0	0	8	1	0	0	1, Guatemala (GUA)	13	0	1	0	1	1	0	0	0	0	14	0	1	0	1, Guyana (GUY) [GUY]	16	0	0	1	1	0	0	0	0	0	16	0	0	1	1, Haiti (HAI) [J]	14	0	1	1	2	0	0	0	0	0	14	0	1	1	2, Hong Kong (HKG) [HKG]	15	1	1	1	3	4	0	0	0	0	19	1	1	1	3, Hungary (HUN)	25	167	144	165	476	22	0	2	4	6	47	167	146	169	482, Iceland (ISL)	19	0	2	2	4	17	0	0	0	0	36	0	2	2	4, India (IND) [F]	23	9	6	11	26	9	0	0	0	0	32	9	6	11	26, Indonesia (INA)	14	6	10	11	27	0	0	0	0	0	14	6	10	11	27, Iran (IRI) [K]	15	15	20	25	60	10	0	0	0	0	25	15	20	25	60, Iraq (IRQ)	13	0	0	1	1	0	0	0	0	0	13	0	0	1	1, Ireland (IRL)	20	9	8	12	29	6	0	0	0	0	26	9	8	12	29, Israel (ISR)	15	1	1	5	7	6	0	0	0	0	21	1	1	5	7, Italy (ITA) [M] [S]	26	198	166	185	549	22	37	34	43	114	48	235	200	228	663, Jamaica (JAM) [JAM]	16	17	30	20	67	7	0	0	0	0	23	17	30	20	67, Japan (JPN)	21	130	126	142	398	20	10	17	18	45	41	140	143	160	443, Kazakhstan (KAZ)	5	16	17	19	52	6	1	3	3	7	11	17	20	22	59, Kenya (KEN)	13	25	32	29	86	3	0	0	0	0	16	25	32	29	86, North Korea (PRK)	9	14	12	21